# syntax=docker.io/docker/dockerfile:1

FROM docker.io/library/debian:trixie-slim

ARG TARGETOS
ARG TARGETARCH
ARG BUILDX_VERSION=v0.33.0
ENV BINARY="buildx-${BUILDX_VERSION}.${TARGETOS}-${TARGETARCH}"

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NOWARNINGS="yes"

ADD --chmod=0755 https://github.com/docker/buildx/releases/download/${BUILDX_VERSION}/${BINARY} /usr/local/bin/buildx

USER nobody
ENTRYPOINT ["/usr/local/bin/buildx"]
