# syntax=docker.io/docker/dockerfile:1

FROM dhi.io/debian-base:trixie-dev

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NOWARNINGS="yes"

USER root
SHELL ["/bin/bash", "-exo", "pipefail", "-c"]

# Default values are overridden by docker-bake.hcl
ARG TOFU_VERSION=1.11.5
ARG KUBECTL_VERSION=v1.33.0
ARG TARGETARCH
ARG DEBIAN_SNAPSHOT_VERSION

# Default UID/GID for tofuuser
ARG UID=1001
ARG GID=1001

# hadolint ignore=DL3008
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked,id=apt-cache-$TARGETARCH --mount=type=cache,target=/var/lib/apt,sharing=locked,id=apt-lib-$TARGETARCH <<-EOF
apt-get update -o Acquire::Check-Valid-Until=false -q --snapshot=${DEBIAN_SNAPSHOT_VERSION}
apt-get install -yq --no-install-recommends --snapshot=${DEBIAN_SNAPSHOT_VERSION} passwd coreutils curl ca-certificates unzip jq
mkdir -p /usr/local/bin

# Install tofu
curl -sLO "https://github.com/opentofu/opentofu/releases/download/v${TOFU_VERSION}/tofu_${TOFU_VERSION}_linux_${TARGETARCH}.zip"
curl -sLO "https://github.com/opentofu/opentofu/releases/download/v${TOFU_VERSION}/tofu_${TOFU_VERSION}_SHA256SUMS"
grep "tofu_${TOFU_VERSION}_linux_${TARGETARCH}.zip" "tofu_${TOFU_VERSION}_SHA256SUMS" | sha256sum --strict --check -
unzip "tofu_${TOFU_VERSION}_linux_${TARGETARCH}.zip" tofu
chmod +x tofu
mv tofu /usr/local/bin/tofu
rm "tofu_${TOFU_VERSION}_linux_${TARGETARCH}.zip" "tofu_${TOFU_VERSION}_SHA256SUMS"

# Install kubectl
curl -sL --remote-name-all "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/${TARGETARCH}/kubectl{,.sha256}"
sed -i 's|$|  kubectl|' kubectl.sha256
sha256sum --strict --check kubectl.sha256
chmod +x kubectl
mv kubectl /usr/local/bin/kubectl
rm kubectl.sha256

groupadd --gid ${GID} tofuuser
useradd --uid ${UID} --gid ${GID} --home-dir /home/tofuuser --create-home --shell /sbin/nologin tofuuser
EOF

USER tofuuser
WORKDIR /home/tofuuser
