# syntax=docker.io/docker/dockerfile:1

ARG UPSTREAM_TAG=3.3.6-debian13
FROM dhi.io/haproxy:${UPSTREAM_TAG}-dev AS builder

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NOWARNINGS="yes"

# hadolint ignore=DL3002
USER root
SHELL ["/bin/bash", "-exo", "pipefail", "-c"]

ARG TARGETARCH

# Default UID/GID for haproxy user
ARG UID=99
ARG GID=99
ARG USERNAME=haproxy
ARG HOME=/var/lib/${USERNAME}

ARG DEBIAN_SNAPSHOT_VERSION="20260405T082808Z"
ENV BUILD_DEPS="mmdebstrap fakeroot"
ENV PRODUCTION_DEPS="ca-certificates lua-json"

# hadolint ignore=DL3008
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked,id=apt-cache-$TARGETARCH --mount=type=cache,target=/var/lib/apt,sharing=locked,id=apt-lib-$TARGETARCH <<-EOF
apt-get update -q --snapshot=${DEBIAN_SNAPSHOT_VERSION}
apt-get install -yq --no-install-recommends --snapshot=${DEBIAN_SNAPSHOT_VERSION} ${BUILD_DEPS}
EOF

# Build rootfs using mmdebstrap
RUN <<-EOF
# Get suite codename from current OS
SUITE=$(. /etc/os-release && echo "${VERSION_CODENAME}")

# Using fixed snapshot archive to ensure reproducible builds
# NB: `Acquire::Check-Valid-Until "false"` required because snapshot archives have expired Release files
fakeroot mmdebstrap \
    --variant=extract \
    --format=directory \
    --mode=chrootless \
    --architectures=${TARGETARCH} \
    --include=${PRODUCTION_DEPS// /,} \
    --setup-hook='mkdir -p "$1/etc" "$1${HOME}"' \
    --setup-hook='echo "${USERNAME}:x:${UID}:${GID}:${USERNAME}}:${HOME}:/sbin/nologin" > "$1/etc/passwd"' \
    --setup-hook='echo "${USERNAME}:x:${GID}:" > "$1/etc/group"' \
    --aptopt='Apt::Install-Recommends "false"' \
    --aptopt='Apt::Install-Suggests "false"' \
    --aptopt='Acquire::Check-Valid-Until "false"' \
    "${SUITE} main" \
    /tmp/rootfs \
    "https://snapshot.debian.org/archive/debian/${DEBIAN_SNAPSHOT_VERSION}"
EOF

# Additional data: GeoIP + IA user-agent lists
ADD --unpack=true https://www.ipdeny.com/ipblocks/data/countries/all-zones.tar.gz /etc/geoip/countries/
ADD https://raw.githubusercontent.com/ai-robots-txt/ai.robots.txt/refs/heads/main/haproxy-block-ai-bots.txt /etc/ia/useragent.lst


FROM dhi.io/haproxy:${UPSTREAM_TAG}

USER root

# Copy system libs and deps
COPY --from=builder /tmp/rootfs /

# Copy geo-blocking & IA country files
COPY --from=builder /etc/geoip /etc/geoip
COPY --from=builder /etc/ia /etc/ia

USER haproxy
ENTRYPOINT ["/opt/haproxy/bin/haproxy"]
CMD ["-db", "-f", "/etc/haproxy"]

STOPSIGNAL SIGUSR1
EXPOSE 8080/tcp 8443/tcp
