# syntax=docker.io/docker/dockerfile-upstream:1.23.0

ARG UPSTREAM_TAG=3.3.6-trixie
FROM docker.io/library/haproxy:${UPSTREAM_TAG} AS haproxy

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NOWARNINGS="yes"

USER root
SHELL ["/bin/bash", "-exo", "pipefail", "-c"]

ARG TARGETARCH

# lua-json is needed to use auth-url & auth-signin with haproxy-ingress
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked,id=apt-cache-$TARGETARCH --mount=type=cache,target=/var/lib/apt,sharing=locked,id=apt-lib-$TARGETARCH <<-EOF
apt-get update -q
apt-get upgrade -y --no-install-recommends
apt-get install -y --no-install-recommends lua-json=1.3.4-3
EOF

USER haproxy
ENTRYPOINT ["/usr/local/sbin/haproxy"]
