# syntax=docker/dockerfile:1.12.0
FROM docker.io/library/haproxy:${UPSTREAM_TAG} AS haproxy

USER root

RUN apt-get update && apt-get upgrade -y --no-install-recommends && \
    apt-get install -y --no-install-recommends lua-json=1.3.4-3 && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

USER haproxy
ENTRYPOINT ["/usr/local/sbin/haproxy"]