# syntax=docker.io/docker/dockerfile-upstream:1.20.0

ARG UPSTREAM_TAG=17-standard-trixie
FROM --platform=${BUILDPLATFORM} ghcr.io/cloudnative-pg/postgresql:${UPSTREAM_TAG}

USER root
SHELL ["/bin/bash", "-exo", "pipefail", "-c"]

ARG PG_MAJOR=17

# hadolint ignore=DL3008
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
<<-EOF
    apt-get update -q
    apt-get install -y --no-install-recommends \
        postgresql-${PG_MAJOR}-repack \
        postgresql-${PG_MAJOR}-cron \
        postgresql-${PG_MAJOR}-partman \
        postgresql-${PG_MAJOR}-pg-stat-kcache \
        postgresql-${PG_MAJOR}-set-user \
        postgresql-${PG_MAJOR}-hypopg \
        postgresql-${PG_MAJOR}-pgextwlist
EOF

USER 26
