# syntax=docker.io/docker/dockerfile-upstream:1.23.0

ARG UPSTREAM_TAG=1.37-debian13
FROM dhi.io/busybox:${UPSTREAM_TAG}

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NOWARNINGS="yes"

USER nonroot
ENTRYPOINT ["/bin/sh"]
